---
title: "Analisis per specie MODEL SUB"
author: "Andrea Chavez"
date: "03-04-2026"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# PRELIMINAR ANALYSIS FOR NUMEX RESULTS.
Here are the analysis at species level. 


```{r libraries}
library(dplyr)
library(tidyverse)
library(glmmTMB)
library(DHARMa)
library(ggplot2)
library(scico)
library(lmerTest)
library(lme4)
library(tables)
library(flextable)
library(readxl)
library(modelsummary)
library(knitr)
library(patchwork)
library("kableExtra")
library("openxlsx")
```

```{r Data}
getwd()

data_for_R <- read_excel('data_for_R.xlsx')

data= data_for_R
```

```{r transformando columnas}

### nutrientes para ver cual funciona mejor.
data$logNmass <- log(data$LNC) #
data$logCmass <- log(data$LCC) #
data$logPmass <- log(data$LPC) #


data$SUB = data$Sub #porque abajo esta en mayuscula

#solo dejar las necesarias
data <- dplyr::select(data,
        `name`,
        `genus`,
        `SUB`,#
        `N`,
        `P`,
        `Bloque`,
        `elevation_m`,
    `iWUE (μmol/mol)`,
    `δ18O in ‰ vs DeltaSMOW`,
    `Specific leaf area (cm²/g)`,
    `δ13C (‰ v.s.V-PDB)`,
    `force to punch (kN/m)`, `Leaf area (cm²)`,`dry matter content (mg/g)`, `thickness (mm)`,`N:P`,`Ci/Ca`, Ci,LNC,LPC,LCC,logNmass,logCmass,logPmass,P_area,N_area,C_area,LA,`LMA g/m2`) 
#Δ13C_cell
```


```{r funcion para graficar}
#plot_coefs <- function(model, title, color = "black",ylim=NULL,show_y=TRUE) {

#  coefs <- broom.mixed::tidy(
 #   model,
  #  effects = "fixed",
  #  conf.int = TRUE,
  #  conf.level = 0.95
  #) %>%
  #  dplyr::filter(term != "(Intercept)") %>%
   # dplyr::mutate(
    #  term = gsub("^Sub", "", term),
     # sig = dplyr::case_when(
  #      p.value < 0.001 ~ "***",
   #     p.value < 0.01  ~ "**",
    #    p.value < 0.05  ~ "*",
     #   TRUE            ~ ""
      #)
  #  )

  #p <- ggplot2::ggplot(coefs, ggplot2::aes(x = term, y = estimate)) +
   # ggplot2::geom_point(size = 3, color = color) +
    #ggplot2::geom_errorbar(
     # ggplot2::aes(ymin = conf.low, ymax = conf.high),
      #width = 0.15,
      #color = color
    #) +
    #ggplot2::geom_text(
    #  ggplot2::aes(
    #    label = sig,
    #    y = conf.high + 0.05 * max(abs(estimate))
    #  ),
    #  vjust = -0.6,
    #  size = 5,
    #  color = color
    #) +
  #  ggplot2::geom_hline(
  ##    linetype = "dashed",
  #    color = "grey40"
  #  ) +
  #  ggplot2::labs(
  #    title = title,
  #    x = "",
  #    y = "Estimate (± 95% CI)"
  #  ) +
  #  ggplot2::scale_y_continuous(expand = ggplot2::expansion(mult = c(0.05, 0.2))) +
  #  ggplot2::coord_cartesian( ylim = ylim,clip = "off") +
   # ggplot2::theme(
    #  axis.text.x = element_text(angle = 45, hjust = 1),
    #  plot.margin = margin(0,0,0,0)
    #)
  
  # if (!show_y) {
   # p <- p +
    #  ggplot2::theme(
     #   axis.title.y = element_blank(),
    #    axis.text.y  = element_blank(),
    #    axis.ticks.y = element_blank()
     # )
  # }
  #  return(p)
#}
```

```{r tabla}


tabla <- function(model_list) {

  tab <- modelsummary(
    model_list,
    output    = "data.frame",
    estimate  = "{estimate}{stars} (SE = {std.error}, p = {p.value})",  # 👈 aquí va todo junto
    statistic = NULL,                                                   # 👈 ya no hace falta línea aparte
    stars     = TRUE,                                                   # necesario para que {stars} se resuelva
    fmt       = 2,                                                      # opcional: controla decimales
    gof_map   = c("nobs", "r2.marginal", "r2.conditional", "aic")
  )

  # Transponer
  tab_t <- as.data.frame(t(tab))

  # Usar primera fila como nombres
  colnames(tab_t) <- as.character(tab_t[1, ])

  # Hacer nombres únicos 
  colnames(tab_t) <- make.unique(colnames(tab_t))

  # Eliminar fila usada como header
  tab_t <- tab_t[-1, , drop = FALSE]

  # Guardar nombres de modelo
  tab_t$Modelo <- rownames(tab_t)
  rownames(tab_t) <- NULL

  # Reordenar columnas
  tab_t <- tab_t[, c("Modelo", setdiff(names(tab_t), "Modelo")), drop = FALSE]

  # Exportar a Excel
  # 👉 Capturar nombre del objeto
  nombre_modelo <- deparse(substitute(model_list))
  file_name <- paste0(nombre_modelo, ".xlsx")
  
  write.xlsx(tab_t, file_name, overwrite = TRUE, asTable = TRUE)

  message("✔ Model saved on excel")

  # Retornar tabla para markdown / PDF / HTML
  return(kbl(tab_t, booktabs = TRUE, align = "l"))
}

``` 

# 1. ISOTOPOS

```{r Filtrando por especie }
datos_Pouteria <- data %>%
filter(data$genus == "Pouteria")

datos_Pouteria <- datos_Pouteria %>%
  filter(!(`iWUE (μmol/mol)` > 55 & SUB == "N")) #Eliminar los outliers.

datos_Clarisia <- data %>%
filter(data$genus == "Clarisia")
datos_al <- data %>%
filter(data$name == "Alchornea lojaensis")
datos_myrcia <- data %>%
filter(data$name == "Myrcia sp nov")
datos_hp <- data %>%
filter(data$genus == "Hedyosmun")
datos_Weinmania <- data %>%
filter(data$genus == "Weinmania")
```


```{r Modelos sin interaccion }
## IWUE

mod_iWUE_pt <- lmer(`iWUE (μmol/mol)` ~ SUB + (1 | Bloque), data = datos_Pouteria)# is Singular 
mod_iWUE_cr <- lmer(`iWUE (μmol/mol)` ~ SUB + (1 | Bloque), data = datos_Clarisia)#is Singular
mod_iWUE_al <- lmer(`iWUE (μmol/mol)` ~ SUB+ (1 | Bloque) , data = datos_al)
mod_iWUE_my <- lmer(`iWUE (μmol/mol)` ~ SUB+(1 | Bloque), data = datos_myrcia)#isSingular
mod_iWUE_hp <- lmer(`iWUE (μmol/mol)` ~SUB+(1 | Bloque), data = datos_hp) #isSingular
mod_iWUE_wl <- lmer(`iWUE (μmol/mol)` ~ SUB+(1 | Bloque), data = datos_Weinmania)

modlm_iWUE_pt <- lm(`iWUE (μmol/mol)` ~ SUB , data = datos_Pouteria)
modlm_iWUE_cr <- lm(`iWUE (μmol/mol)` ~ SUB , data = datos_Clarisia)
modlm_iWUE_al <- lm(`iWUE (μmol/mol)` ~ SUB , data = datos_al)
modlm_iWUE_my <- lm(`iWUE (μmol/mol)` ~ SUB , data = datos_myrcia)
modlm_iWUE_hp <- lm(`iWUE (μmol/mol)` ~SUB, data = datos_hp) 
modlm_iWUE_wl <- lm(`iWUE (μmol/mol)` ~ SUB , data = datos_Weinmania)

summary(mod_iWUE_pt)
summary(mod_iWUE_cr)
summary(mod_iWUE_al)
summary(mod_iWUE_my)
summary(mod_iWUE_hp)
summary(mod_iWUE_wl)

summary(modlm_iWUE_pt)
summary(modlm_iWUE_cr)
summary(modlm_iWUE_al)
summary(modlm_iWUE_my)
summary(modlm_iWUE_hp)
summary(modlm_iWUE_wl)
### C13 
mod_C13_pt <- lmer(`δ13C (‰ v.s.V-PDB)` ~ SUB + (1 | Bloque), data = datos_Pouteria)
mod_C13_cr <- lmer(`δ13C (‰ v.s.V-PDB)` ~ SUB + (1 | Bloque), data = datos_Clarisia)
mod_C13_al <- lmer(`δ13C (‰ v.s.V-PDB)` ~ SUB + (1 | Bloque), data = datos_al)
mod_C13_my <- lmer(`δ13C (‰ v.s.V-PDB)` ~ SUB + (1 | Bloque), data = datos_myrcia)
mod_C13_hp <- lmer(`δ13C (‰ v.s.V-PDB)` ~ SUB + (1 | Bloque), data = datos_hp)
mod_C13_wl <- lmer(`δ13C (‰ v.s.V-PDB)` ~ SUB + (1 | Bloque), data = datos_Weinmania)

summary(mod_C13_pt)
summary(mod_C13_cr)
summary(mod_C13_al)
summary(mod_C13_my)
summary(mod_C13_hp)
summary(mod_C13_wl)


mod_Ci_pt <- lmer(`Ci/Ca` ~ SUB + (1 | Bloque), data = datos_Pouteria)
mod_Ci_cr <- lmer(`Ci/Ca` ~ SUB + (1 | Bloque), data = datos_Clarisia)
mod_Ci_al <- lmer(`Ci/Ca` ~ SUB + (1 | Bloque), data = datos_al)
mod_Ci_my <- lmer(`Ci/Ca`~ SUB + (1 | Bloque), data = datos_myrcia)
mod_Ci_hp <- lmer(`Ci/Ca`~ SUB + (1 | Bloque), data = datos_hp)
mod_Ci_wl <- lmer(`Ci/Ca` ~ SUB + (1 | Bloque), data = datos_Weinmania)
```


```{r listado}
#source("tabla_SUB.R")

models_iWUE<- list(

# iWUE
"iWUE | 1000 | Pouteria" = mod_iWUE_pt,
"iWUE | 1000 | Clarisia" = mod_iWUE_cr,
"iWUE | 2000 | Alchornea" = mod_iWUE_al,
"iWUE | 2000 | Myrcia" = mod_iWUE_my,
"iWUE | 3000 | Hedyosmum" = mod_iWUE_hp,
"iWUE | 3000 | Weinmannia" = mod_iWUE_wl,

# δ13C
"δ13C | 1000 | Pouteria" = mod_C13_pt,
"δ13C | 1000 | Clarisia" = mod_C13_cr,
"δ13C | 2000 | Alchornea" = mod_C13_al,
"δ13C | 2000 | Myrcia" = mod_C13_my,
"δ13C | 3000 | Hedyosmum" = mod_C13_hp,
"δ13C | 3000 | Weinmannia" = mod_C13_wl,

# δ18O
"Ci | 1000 | Pouteria" = mod_Ci_pt,
"Ci | 1000 | Clarisia" = mod_Ci_cr,
"Ci | 2000 | Alchornea" = mod_Ci_al,
"Ci | 2000 | Myrcia" = mod_Ci_my,
"Ci | 3000 | Hedyosmum" = mod_Ci_hp,
"Ci | 3000 | Weinmannia" = mod_Ci_wl)
```
## 1.1. Tabla
```{r tabla 1}
tabla(models_iWUE)
```

## 1.2. Diagnostico
```{r Diagnostico modelos isotopos}
par(mfrow = c(2, 2))  # 4 modelos por página

for (name in names(models_iWUE)) {
  m <- models_iWUE[[name]]
  r <- resid(m)
  f <- fitted(m)
  
  # 1. Residuales vs Fitted
  plot(f, r,
       main = paste(name, "- Residuals"),
       xlab = "Fitted values",
       ylab = "Residuals")
  abline(h = 0, col = "red")
  
  # 2. QQ plot
  qqnorm(r, main = paste(name, "- QQ plot"))
  qqline(r, col = "red")
}
```

# 2. NUTRIENTES
```{r modelos ESTEOQUEMETRIA}

###### NITROGEN ############
mod_Nmass_pt <- lmer(LNC ~ SUB+ (1 | Bloque), data = datos_Pouteria)
mod_Nmass_cr <- lmer(LNC ~ SUB+ (1 | Bloque), data = datos_Clarisia)
mod_Nmass_my <- lmer(LNC ~ SUB+ (1 | Bloque), data = datos_myrcia)
mod_Nmass_al <- lmer(LNC ~ SUB+ (1 | Bloque), data = datos_al)
mod_Nmass_wl <- lmer(LNC ~ SUB+ (1 | Bloque), data = datos_Weinmania)
mod_Nmass_hp <- lmer(LNC ~ SUB+ (1 | Bloque), data = datos_hp)

######## PHOSPHORUS ############
mod_Pmass_pt <- lmer(LPC ~ SUB+ (1 | Bloque), data = datos_Pouteria)
mod_Pmass_cr <- lmer(LPC ~ SUB+ (1 | Bloque), data = datos_Clarisia)
mod_Pmass_my <- lmer(LPC ~ SUB+ (1 | Bloque), data = datos_myrcia)
mod_Pmass_al <- lmer(LPC ~ SUB+ (1 | Bloque), data = datos_al)
mod_Pmass_wl <- lmer(LPC ~ SUB+ (1 | Bloque), data = datos_Weinmania)
mod_Pmass_hp <- lmer(LPC ~ SUB+ (1 | Bloque), data = datos_hp)

########## CARBON ################
mod_Cmass_pt <- lmer(LCC ~ SUB + (1 | Bloque), data = datos_Pouteria)
mod_Cmass_cr <- lmer(LCC ~ SUB + (1 | Bloque), data = datos_Clarisia)
mod_Cmass_al <- lmer(LCC ~ SUB + (1 | Bloque), data = datos_al)
mod_Cmass_my <- lmer(LCC ~ SUB + (1 | Bloque), data = datos_myrcia)
mod_Cmass_hp <- lmer(LCC ~ SUB + (1 | Bloque), data = datos_hp)
mod_Cmass_wl <- lmer(LCC ~ SUB + (1 | Bloque), data = datos_Weinmania)

mod_logNmass_pt <- lmer(`logNmass` ~ SUB+ (1 | Bloque), data = datos_Pouteria)
mod_logNmass_cr <- lmer(`logNmass` ~ SUB+ (1 | Bloque), data = datos_Clarisia)
mod_logNmass_my <- lmer(`logNmass` ~ SUB+ (1 | Bloque), data = datos_myrcia)
mod_logNmass_al <- lmer(`logNmass` ~ SUB+ (1 | Bloque), data = datos_al)
mod_logNmass_wl <- lmer(`logNmass` ~ SUB+ (1 | Bloque), data = datos_Weinmania)
mod_logNmass_hp <- lmer(`logNmass` ~ SUB+ (1 | Bloque), data = datos_hp)

mod_logPmass_pt <- lmer(`logPmass` ~ SUB+ (1 | Bloque), data = datos_Pouteria)
mod_logPmass_cr <- lmer(`logPmass` ~ SUB+ (1 | Bloque), data = datos_Clarisia)
mod_logPmass_my <- lmer(`logPmass` ~ SUB+ (1 | Bloque), data = datos_myrcia)
mod_logPmass_al <- lmer(`logPmass` ~ SUB+ (1 | Bloque), data = datos_al)
mod_logPmass_wl <- lmer(`logPmass` ~ SUB+ (1 | Bloque), data = datos_Weinmania)
mod_logPmass_hp <- lmer(`logPmass` ~ SUB+ (1 | Bloque), data = datos_hp)

mod_logCmass_pt <- lmer(`logCmass` ~ SUB+ (1 | Bloque), data = datos_Pouteria)
mod_logCmass_cr <- lmer(`logCmass` ~ SUB+ (1 | Bloque), data = datos_Clarisia)
mod_logCmass_my <- lmer(`logCmass` ~ SUB+ (1 | Bloque), data = datos_myrcia)
mod_logCmass_al <- lmer(`logCmass` ~ SUB+ (1 | Bloque), data = datos_al)
mod_logCmass_wl <- lmer(`logCmass` ~ SUB+ (1 | Bloque), data = datos_Weinmania)
mod_logCmass_hp <- lmer(`logCmass` ~ SUB+ (1 | Bloque), data = datos_hp)

mod_Narea_pt <- lmer(`N_area` ~ SUB+ (1 | Bloque), data = datos_Pouteria)
mod_Narea_cr <- lmer(`N_area` ~ SUB+ (1 | Bloque), data = datos_Clarisia)
mod_Narea_my <- lmer(`N_area` ~ SUB+ (1 | Bloque), data = datos_myrcia)
mod_Narea_wl <- lmer(`N_area` ~ SUB+ (1 | Bloque), data = datos_Weinmania)
mod_Narea_al <- lmer(`N_area` ~ SUB+ (1 | Bloque), data = datos_al)
mod_Narea_hp <- lmer(`N_area` ~ SUB+ (1 | Bloque), data = datos_hp)

######## PHOSPHORUS ############
mod_Parea_pt <- lmer(`P_area` ~ SUB+ (1 | Bloque), data = datos_Pouteria)
mod_Parea_cr <- lmer(`P_area` ~ SUB+ (1 | Bloque), data = datos_Clarisia)
mod_Parea_my <- lmer(`P_area` ~ SUB+ (1 | Bloque), data = datos_myrcia)
mod_Parea_wl <- lmer(`P_area` ~ SUB+ (1 | Bloque), data = datos_Weinmania)
mod_Parea_al <- lmer(`P_area` ~ SUB+ (1 | Bloque), data = datos_al)
mod_Parea_hp <- lmer(`P_area` ~ SUB+ (1 | Bloque), data = datos_hp)

########## CARBON ################
mod_Carea_pt <- lmer(C_area ~ SUB + (1 | Bloque), data = datos_Pouteria)
mod_Carea_cr <- lmer(C_area ~ SUB + (1 | Bloque), data = datos_Clarisia)
mod_Carea_al <- lmer(C_area ~ SUB + (1 | Bloque), data = datos_al)
mod_Carea_my <- lmer(C_area ~ SUB + (1 | Bloque), data = datos_myrcia)
mod_Carea_hp <- lmer(C_area ~ SUB + (1 | Bloque), data = datos_hp)
mod_Carea_wl <- lmer(C_area ~ SUB + (1 | Bloque), data = datos_Weinmania)

mod_fol_NP_pt <- lmer(`N:P` ~ SUB + (1 | Bloque), data = datos_Pouteria)
mod_fol_NP_cr <- lmer(`N:P` ~ SUB + (1 | Bloque), data = datos_Clarisia)
mod_fol_NP_al <- lmer(`N:P` ~ SUB + (1 | Bloque), data = datos_al)
mod_fol_NP_my <- lmer(`N:P` ~ SUB + (1 | Bloque), data = datos_myrcia)
mod_fol_NP_hp <- lmer(`N:P` ~ SUB + (1 | Bloque), data = datos_hp)
mod_fol_NP_wl <- lmer(`N:P` ~ SUB + (1 | Bloque), data = datos_Weinmania)

```
```{r estq}

models_est <- list(
# Nmass
"Nmass | 1000 | Pouteria" = mod_Nmass_pt,
"Nmass | 1000 | Clarisia" = mod_Nmass_cr,
"Nmass | 2000 | Alchornea" = mod_Nmass_al,
"Nmass | 2000 | Myrcia" = mod_Nmass_my,
"Nmass | 3000 | Hedyosmum" = mod_Nmass_hp,
"Nmass | 3000 | Weinmannia" = mod_Nmass_wl,

"logNmass | 1000 | Pouteria" = mod_logNmass_pt,
"logNmass | 1000 | Clarisia" = mod_logNmass_cr,
"logNmass | 2000 | Alchornea" = mod_logNmass_al,
"logNmass | 2000 | Myrcia" = mod_logNmass_my,
"logNmass | 3000 | Hedyosmum" = mod_logNmass_hp,
"logNmass | 3000 | Weinmannia" = mod_logNmass_wl,

# Narea
"Narea | 1000 | Pouteria" = mod_Narea_pt,
"Narea | 1000 | Clarisia" = mod_Narea_cr,
"Narea | 2000 | Alchornea" = mod_Narea_al,
"Narea | 2000 | Myrcia" = mod_Narea_my,
"Narea | 3000 | Hedyosmum" = mod_Narea_hp,
"Narea | 3000 | Weinmannia" = mod_Narea_wl,

# Cmass
"Cmass | 1000 | Pouteria" = mod_Cmass_pt,
"Cmass | 1000 | Clarisia" = mod_Cmass_cr,
"Cmass | 2000 | Alchornea" = mod_Cmass_al,
"Cmass | 2000 | Myrcia" = mod_Cmass_my,
"Cmass | 3000 | Hedyosmum" = mod_Cmass_hp,
"Cmass | 3000 | Weinmannia" = mod_Cmass_wl,

# Carea
"Carea | 1000 | Pouteria" = mod_Carea_pt,
"Carea | 1000 | Clarisia" = mod_Carea_cr,
"Carea | 2000 | Alchornea" = mod_Carea_al,
"Carea | 2000 | Myrcia" = mod_Carea_my,
"Carea | 3000 | Hedyosmum" = mod_Carea_hp,
"Carea | 3000 | Weinmannia" = mod_Carea_wl,

"logLCCC | 1000 | Pouteria" = mod_logCmass_pt,
"logLCCC |1000 | Clarisia" = mod_logCmass_cr,
"logLCCC  | 2000 | Alchornea" = mod_logCmass_al,
"logLCCC  | 2000 | Myrcia" = mod_logCmass_my,
"logLCCC  | 3000 | Hedyosmum" = mod_logCmass_hp,
"logLCCC  | 3000 | Weinmannia" = mod_logCmass_wl,

# Pmass
"LPC | 1000 | Pouteria" = mod_Pmass_pt,
"LPC | 1000 | Clarisia" = mod_Pmass_cr,
"LPC | 2000 | Alchornea" = mod_Pmass_al,
"LPC | 2000 | Myrcia" = mod_Pmass_my,
"LPC | 3000 | Hedyosmum" = mod_Pmass_hp,
"LPC | 3000 | Weinmannia" = mod_Pmass_wl,

"logLPC | 1000 | Pouteria" = mod_logPmass_pt,
"logLPC | 1000 | Clarisia" = mod_logPmass_cr,
"logLPC | 2000 | Alchornea" = mod_logPmass_al,
"logLPC | 2000 | Myrcia" = mod_logPmass_my,
"logLPC | 3000 | Hedyosmum" = mod_logPmass_hp,
"logLPC | 3000 | Weinmannia" = mod_logPmass_wl,

# Carea
"Parea | 1000 | Pouteria" = mod_Parea_pt,
"Parea | 1000 | Clarisia" = mod_Parea_cr,
"Parea | 2000 | Alchornea" = mod_Parea_al,
"Parea | 2000 | Myrcia" = mod_Parea_my,
"Parea | 3000 | Hedyosmum" = mod_Parea_hp,
"Parea | 3000 | Weinmannia" = mod_Parea_wl,

"Leaf N:P | 1000 | Pouteria" = mod_fol_NP_pt,
"Leaf N:P | 1000 | Clarisia" = mod_fol_NP_cr,
"Leaf N:P | 2000 | Alchornea" = mod_fol_NP_al,
"Leaf N:P | 2000 | Myrcia" = mod_fol_NP_my,
"Leaf N:P | 3000 | Hedyosmum" = mod_fol_NP_hp,
"Leaf N:P | 3000 | Weinmannia" = mod_fol_NP_wl
)

```
## 2.1. Tabla
```{r tabla 2}
tabla(models_est)
```

## 2.2. Diagnostico
```{r DIAGNOSTICO}
par(mfrow = c(2, 2))  # 4 modelos por página

for (name in names(models_est)) {
  m <- models_est[[name]]
  r <- resid(m)
  f <- fitted(m)
  
  # 1. Residuales vs Fitted
  plot(f, r,
       main = paste(name, "- Residuals"),
       xlab = "Fitted values",
       ylab = "Residuals")
  abline(h = 0, col = "red")
  
  # 2. QQ plot
  qqnorm(r, main = paste(name, "- QQ plot"))
  qqline(r, col = "red")
}
```


#3. MORPHOLOGICAL

```{r morpho}
mod_SLA_pt <- lmer(`Specific leaf area (cm²/g)` ~ SUB+ (1 | Bloque), data = datos_Pouteria)
mod_SLA_cr <- lmer(`Specific leaf area (cm²/g)` ~ SUB+ (1 | Bloque), data = datos_Clarisia)
mod_SLA_al <- lmer(`Specific leaf area (cm²/g)` ~ SUB+ (1 | Bloque), data = datos_al)
mod_SLA_my <- lmer(`Specific leaf area (cm²/g)` ~ SUB+ (1 | Bloque), data = datos_myrcia)
mod_SLA_hp <- lmer(`Specific leaf area (cm²/g)` ~ SUB+ (1 | Bloque), data = datos_hp)
mod_SLA_wl <- lmer(`Specific leaf area (cm²/g)` ~ SUB+ (1 | Bloque), data = datos_Weinmania)
summary(mod_SLA_pt )
summary(mod_SLA_cr )
summary(mod_SLA_al )
summary(mod_SLA_my )
summary(mod_SLA_hp )
summary(mod_SLA_wl )

mod_Thick_pt <- lmer( `thickness (mm)`~ SUB+ (1 | Bloque), data = datos_Pouteria)
mod_Thick_cr <- lmer(`thickness (mm)` ~ SUB+ (1 | Bloque), data = datos_Clarisia)
mod_Thick_al <- lmer(`thickness (mm)` ~ SUB+ (1 | Bloque), data = datos_al)
mod_Thick_my <- lmer(`thickness (mm)` ~ SUB+ (1 | Bloque), data = datos_myrcia)
mod_Thick_hp <- lmer(`thickness (mm)` ~ SUB+ (1 | Bloque), data = datos_hp)
mod_Thick_wl <- lmer(`thickness (mm)` ~ SUB+ (1 | Bloque), data = datos_Weinmania)

mod_Tough_pt <- lmer(`force to punch (kN/m)` ~ SUB+ (1 | Bloque), data = datos_Pouteria)
mod_Tough_cr <- lmer(`force to punch (kN/m)`~ SUB+ (1 | Bloque), data = datos_Clarisia)
mod_Tough_al <- lmer(`force to punch (kN/m)` ~ SUB+ (1 | Bloque), data = datos_al)
mod_Tough_my <- lmer(`force to punch (kN/m)` ~ SUB+ (1 | Bloque), data = datos_myrcia)
mod_Tough_hp <- lmer(`force to punch (kN/m)` ~ SUB+ (1 | Bloque), data = datos_hp)
mod_Tough_wl <- lmer(`force to punch (kN/m)` ~ SUB+ (1 | Bloque), data = datos_Weinmania)


mod_la_pt <- lmer(`LA` ~ SUB+ (1 | Bloque), data = datos_Pouteria)
mod_la_cr <- lmer(`LA`~ SUB+ (1 | Bloque), data = datos_Clarisia)
mod_la_al <- lmer(`LA` ~ SUB+ (1 | Bloque), data = datos_al)
mod_la_my <- lmer(`LA` ~ SUB+ (1 | Bloque), data = datos_myrcia)
mod_la_hp <- lmer(`LA` ~ SUB+ (1 | Bloque), data = datos_hp)
mod_la_wl <- lmer(`LA` ~ SUB+ (1 | Bloque), data = datos_Weinmania)
summary(mod_la_pt )
summary(mod_la_cr )
summary(mod_la_al )
summary(mod_la_my )
summary(mod_la_hp )
summary(mod_la_wl )

mod_lma_pt <- lmer(`LMA g/m2` ~ SUB+ (1 | Bloque), data = datos_Pouteria)
mod_lma_cr <- lmer(`LMA g/m2`~ SUB+ (1 | Bloque), data = datos_Clarisia)
mod_lma_al <- lmer(`LMA g/m2` ~ SUB+ (1 | Bloque), data = datos_al)
mod_lma_my <- lmer(`LMA g/m2`~ SUB+ (1 | Bloque), data = datos_myrcia)
mod_lma_hp <- lmer(`LMA g/m2` ~ SUB+ (1 | Bloque), data = datos_hp)
mod_lma_wl <- lmer(`LMA g/m2` ~ SUB+ (1 | Bloque), data = datos_Weinmania)
summary(mod_lma_pt )
summary(mod_lma_cr )
summary(mod_lma_al )
summary(mod_lma_my )
summary(mod_lma_hp )
summary(mod_lma_wl )



mod_dmc_pt <- lmer(`dry matter content (mg/g)` ~ SUB+ (1 | Bloque), data = datos_Pouteria)
mod_dmc_cr <- lmer(`dry matter content (mg/g)`~ SUB+ (1 | Bloque), data = datos_Clarisia)
mod_dmc_al <- lmer(`dry matter content (mg/g)` ~ SUB+ (1 | Bloque), data = datos_al)
mod_dmc_my <- lmer(`dry matter content (mg/g)` ~ SUB+ (1 | Bloque), data = datos_myrcia)
mod_dmc_hp <- lmer(`dry matter content (mg/g)` ~ SUB+ (1 | Bloque), data = datos_hp)
mod_dmc_wl <- lmer(`dry matter content (mg/g)` ~ SUB+ (1 | Bloque), data = datos_Weinmania)

```

```{r listado morpho}

models_leaf <- list(

# SLA
"SLA | 1000 | Pouteria" = mod_SLA_pt,
"SLA | 1000 | Clarisia" = mod_SLA_cr,
"SLA | 2000 | Alchornea" = mod_SLA_al,
"SLA | 2000 | Myrcia" = mod_SLA_my,
"SLA | 3000 | Hedyosmum" = mod_SLA_hp,
"SLA | 3000 | Weinmannia" = mod_SLA_wl,

# Thickness
"Thickness | 1000 | Pouteria" = mod_Thick_pt,
"Thickness | 1000 | Clarisia" = mod_Thick_cr,
"Thickness | 2000 | Alchornea" = mod_Thick_al,
"Thickness | 2000 | Myrcia" = mod_Thick_my,
"Thickness | 3000 | Hedyosmum" = mod_Thick_hp,
"Thickness | 3000 | Weinmannia" = mod_Thick_wl,

# Toughness
"Toughness | 1000 | Pouteria" = mod_Tough_pt,
"Toughness | 1000 | Clarisia" = mod_Tough_cr,
"Toughness | 2000 | Alchornea" = mod_Tough_al,
"Toughness | 2000 | Myrcia" = mod_Tough_my,
"Toughness | 3000 | Hedyosmum" = mod_Tough_hp,
"Toughness | 3000 | Weinmannia" = mod_Tough_wl,

# Le
"LA | 1000 | Pouteria" = mod_la_pt,
"LA | 1000 | Clarisia" = mod_la_cr,
"LA | 2000 | Alchornea" = mod_la_al,
"LA| 2000 | Myrcia" = mod_la_my,
"LA | 3000 | Hedyosmum" = mod_la_hp,
"LA | 3000 | Weinmannia" = mod_la_wl,

# DMC
"DMC | 1000 | Pouteria" = mod_dmc_pt,
"DMC | 1000 | Clarisia" = mod_dmc_cr,
"DMC | 2000 | Alchornea" = mod_dmc_al,
"DMC 2000 | Myrcia" = mod_dmc_my,
"DMC | 3000 | Hedyosmum" = mod_dmc_hp,
"DMC | 3000 | Weinmannia" = mod_dmc_wl


)
```

## 3.1 Tabla
```{r tabla 3}
tabla(models_leaf)
```

## 3.2 Diagnostico.
```{r}

par(mfrow = c(2, 2))  # 4 modelos por página

for (name in names(models_leaf)) {
  m <- models_leaf[[name]]
  r <- resid(m)
  f <- fitted(m)
  
  # 1. Residuales vs Fitted
  plot(f, r,
       main = paste(name, "- Residuals"),
       xlab = "Fitted values",
       ylab = "Residuals")
  abline(h = 0, col = "red")
  
  # 2. QQ plot
  qqnorm(r, main = paste(name, "- QQ plot"))
  qqline(r, col = "red")
}
```
## 4. GRAFICOS

```{r GGPLOT }

p1_iWUE <- plot_coefs(mod_iWUE_pt, "P. torta",color="#458B74")
p2_iWUE <- plot_coefs(mod_iWUE_cr, "C. racemosa",color="#458B74")
p3_iWUE <- plot_coefs(mod_iWUE_my, "M. sp",color="#458B74")
p4_iWUE <- plot_coefs(mod_iWUE_al, "A. lojaensis",color="#458B74")
p5_iWUE <- plot_coefs(mod_iWUE_hp, "H. purpurascens",color="#458B74")
p6_iWUE <- plot_coefs(mod_iWUE_wl, "W. loxensis",color="#458B74")

p1_Narea <- plot_coefs(mod_Narea_pt, "P.torta",color="#458B00")
p2_Narea <- plot_coefs(mod_Narea_cr, "C. racemosa",color="#458B00")
p3_Narea <- plot_coefs(mod_Narea_my, "M. sp",color="#458B00")
p4_Narea <- plot_coefs(mod_Narea_al, "A. lojaensis",color="#458B00")
p5_Narea <- plot_coefs(mod_Narea_hp, "H. purpurascens",color="#458B00")
p6_Narea <- plot_coefs(mod_Narea_wl, "W. loxensis",color="#458B00")

p1_Parea <- plot_coefs(mod_Parea_pt, "P.torta",color="#CD5B45")
p2_Parea <- plot_coefs(mod_Parea_cr, "C. racemosa",color="#CD5B45")
p3_Parea <- plot_coefs(mod_Parea_my, "M. sp",color="#CD5B45")
p4_Parea <- plot_coefs(mod_Parea_al, "A. lojaensis",color="#CD5B45")
p5_Parea <- plot_coefs(mod_Parea_hp, "H. purpurascens",color="#CD5B45")
p6_Parea <- plot_coefs(mod_Parea_wl, "W. loxensis",color="#CD5B45")

p1_SLA <- plot_coefs(mod_SLA_pt, "P. torta",color="#CD661D")
p2_SLA <- plot_coefs(mod_SLA_cr, "C. racemosa",color="#CD661D")
p3_SLA <- plot_coefs(mod_SLA_my, "M. sp",color="#CD661D")
p4_SLA <- plot_coefs(mod_SLA_al, "A. lojaensis",color="#CD661D")
p5_SLA <- plot_coefs(mod_SLA_hp, "H. purpurascens",color="#CD661D")
p6_SLA <- plot_coefs(mod_SLA_wl, "W. loxensis",color="#CD661D")

library(patchwork)

library(broom.mixed)
library(dplyr)

mods_iWUE <- list(
  mod_iWUE_pt,
 mod_iWUE_cr,
 mod_iWUE_al,
  mod_iWUE_my,
  mod_iWUE_hp,
  mod_iWUE_wl
)

all_coefs <- lapply(mods_iWUE, function(m){

  broom.mixed::tidy(
    m,
    effects = "fixed",
    conf.int = TRUE
  ) %>%
  filter(term != "(Intercept)")

}) %>%
bind_rows()

ylim_iWUE <- c(
  min(all_coefs$conf.low),
  max(all_coefs$conf.high)
)
p1_iWUE <- plot_coefs(
  mod_iWUE_pt,
  "Species 1",
  ylim = ylim_iWUE,
  show_y = TRUE
)

p2_iWUE <- plot_coefs(
  mod_iWUE_cr,
  "Species 2",
  ylim = ylim_iWUE,
  show_y = FALSE
)

p3_iWUE <- plot_coefs(
  mod_iWUE_al,
  "Species 3",
  ylim = ylim_iWUE,
  show_y = FALSE
)

final_plot <-
(
  p1_iWUE  | p2_iWUE  | p3_iWUE  | p4_iWUE  | p5_iWUE  | p6_iWUE
) /
(
  p1_Narea | p2_Narea | p3_Narea | p4_Narea | p5_Narea | p6_Narea
) /
(
  p1_Parea | p2_Parea | p3_Parea | p4_Parea | p5_Parea | p6_Parea
) +
plot_layout(
  guides = "collect"
) &
theme(
  panel.spacing = unit(0, "lines"),
  plot.margin = margin(0,0,0,0),
  legend.position = "bottom"
)

final_plot


```
## 4.2. GRAFICOS 2
```{r GGPLOT2}

#p1_iWUE <- plot_coefs(mod_iWUE_pt, "P. torta",color="#458B74")
#p2_iWUE <- plot_coefs(mod_iWUE_cr, "C. racemosa",color="#458B74")
#p3_iWUE <- plot_coefs(mod_iWUE_my, "M. sp",color="#458B74")
#p4_iWUE <- plot_coefs(mod_iWUE_al, "A. lojaensis",color="#458B74")
#p5_iWUE <- plot_coefs(mod_iWUE_hp, "H. purpurascens",color="#458B74")
#p6_iWUE <- plot_coefs(mod_iWUE_wl, "W. loxensis",color="#458B74")

#logNmass
#p1_Narea <- plot_coefs(mod_logNmass_pt, "P.torta",color="#458B00")
#p2_Narea <- plot_coefs(mod_logNmass_cr, "C. racemosa",color="#458B00")
#p3_Narea <- plot_coefs(mod_logNmass_my, "M. sp",color="#458B00")
#p4_Narea <- plot_coefs(mod_logNmass_al, "A. lojaensis",color="#458B00")
#p5_Narea <- plot_coefs(mod_logNmass_hp, "H. purpurascens",color="#458B00")
#p6_Narea <- plot_coefs(mod_logNmass_wl, "W. loxensis",color="#458B00")

#p1_Parea <- plot_coefs(mod_logPmass_pt, "P.torta",color="#CD5B45")
#p2_Parea <- plot_coefs(mod_logPmass_cr, "C. racemosa",color="#CD5B45")
#p3_Parea <- plot_coefs(mod_logPmass_my, "M. sp",color="#CD5B45")
#p4_Parea <- plot_coefs(mod_logPmass_al, "A. lojaensis",color="#CD5B45")
#p5_Parea <- plot_coefs(mod_logPmass_hp, "H. purpurascens",color="#CD5B45")
#p6_Parea <- plot_coefs(mod_logPmass_wl, "W. loxensis",color="#CD5B45")


#p1_SLA <- plot_coefs(mod_fol_NP_pt
#, "P. torta",color="#CD661D")
#p2_SLA <- plot_coefs(mod_fol_NP_cr, "C. racemosa",color="#CD661D")
#p3_SLA <- plot_coefs(mod_fol_NP_my, "M. sp",color="#CD661D")
#p4_SLA <- plot_coefs(mod_fol_NP_al, "A. lojaensis",color="#CD661D")
#p5_SLA <- plot_coefs(mod_fol_NP_hp, "H. purpurascens",color="#CD661D")
#p6_SLA <- plot_coefs(mod_fol_NP_wl, "W. loxensis",color="#CD661D")

#remove_title <- theme(plot.title = element_blank())

# aplicar a todas menos la primera fila
#p1_Narea <- p1_Narea + remove_title
#p2_Narea <- p2_Narea + remove_title
#p3_Narea <- p3_Narea + remove_title
#p4_Narea <- p4_Narea + remove_title
#p5_Narea <- p5_Narea + remove_title
#p6_Narea <- p6_Narea + remove_title

#p1_Parea <- p1_Parea + remove_title
#p2_Parea <- p2_Parea + remove_title
#p3_Parea <- p3_Parea + remove_title
#p4_Parea <- p4_Parea + remove_title
#p5_Parea <- p5_Parea + remove_title
#p6_Parea <- p6_Parea + remove_title

#p1_SLA <- p1_SLA + remove_title
#p2_SLA <- p2_SLA + remove_title
#p3_SLA <- p3_SLA + remove_title
#p4_SLA <- p4_SLA + remove_title
#p5_SLA <- p5_SLA + remove_title
#p6_SLA <- p6_SLA + remove_title


#final_plot <- (p1_iWUE  | p2_iWUE  | p3_iWUE  | p4_iWUE  | p5_iWUE  | p6_iWUE) /
#              (p1_Narea | p2_Narea | p3_Narea | p4_Narea | p5_Narea | p6_Narea) /
#              (p1_Parea | p2_Parea | p3_Parea | p4_Parea | p5_Parea | p6_Parea) /
#              (p1_SLA  | p2_SLA  | p3_SLA  | p4_SLA  | p5_SLA  | p6_SLA)

#ggsave("figure_poster.png",
 #      plot = final_plot,
  #     width = 16, height = 12,  # ajusta según tu póster
   #    dpi = 300)               # 300–600 para alta calidad

```



## TEST ADICIONALES Narea y Parea 

```{r test Narea}

mod_iwue_narea_pt = lmer(`iWUE (μmol/mol)`~ N_area+SUB +(1|Bloque), data = datos_Pouteria)
mod_iwue_narea_cr= lmer(`iWUE (μmol/mol)`~ N_area+SUB +(1|Bloque), data = datos_Clarisia)
mod_iwue_narea_al= lmer(`iWUE (μmol/mol)`~ N_area+SUB +(1|Bloque), data = datos_al)
mod_iwue_narea_my= lmer(`iWUE (μmol/mol)`~ N_area+SUB +(1|Bloque), data = datos_myrcia)
mod_iwue_narea_hp= lmer(`iWUE (μmol/mol)`~ N_area+SUB +(1|Bloque), data = datos_hp)
mod_iwue_narea_we= lmer(`iWUE (μmol/mol)`~ N_area+SUB +(1|Bloque), data = datos_Weinmania)

imod_iwue_narea_pt = lmer(`iWUE (μmol/mol)`~ N_area*SUB +(1|Bloque), data = datos_Pouteria)
imod_iwue_narea_cr= lmer(`iWUE (μmol/mol)`~ N_area*SUB +(1|Bloque), data = datos_Clarisia)
imod_iwue_narea_al= lmer(`iWUE (μmol/mol)`~ N_area*SUB +(1|Bloque), data = datos_al)
imod_iwue_narea_my= lmer(`iWUE (μmol/mol)`~ N_area*SUB +(1|Bloque), data = datos_myrcia)
imod_iwue_narea_hp= lmer(`iWUE (μmol/mol)`~ N_area*SUB +(1|Bloque), data = datos_hp)
imod_iwue_narea_we= lmer(`iWUE (μmol/mol)`~ N_area*SUB +(1|Bloque), data = datos_Weinmania)


summary(mod_iwue_narea_pt)
summary(mod_iwue_narea_cr)
summary(mod_iwue_narea_al)
summary(mod_iwue_narea_my)
summary(mod_iwue_narea_hp)
summary(mod_iwue_narea_we)
summary(imod_iwue_narea_pt)
summary(imod_iwue_narea_cr)
summary(imod_iwue_narea_al)
summary(imod_iwue_narea_my)
summary(imod_iwue_narea_hp)
summary(imod_iwue_narea_we)

#mod1 <- lmer(`iWUE (μmol/mol)` ~ SUB + (1|Bloque), data = datos_Clarisia)

#mod2 <- lmer(`iWUE (μmol/mol)` ~ Narea + SUB + (1|Bloque), data = datos_Clarisia)

#anova(mod1, mod2)


mod_iwue_Parea_pt = lmer(`iWUE (μmol/mol)`~ P_area+SUB +(1|Bloque), data = datos_Pouteria)
mod_iwue_Parea_cr= lmer(`iWUE (μmol/mol)`~ P_area+SUB +(1|Bloque), data = datos_Clarisia)
mod_iwue_Parea_al= lmer(`iWUE (μmol/mol)`~ P_area+SUB +(1|Bloque), data = datos_al)
mod_iwue_Parea_my= lmer(`iWUE (μmol/mol)`~ P_area+SUB +(1|Bloque), data = datos_myrcia)
mod_iwue_Parea_hp= lmer(`iWUE (μmol/mol)`~ P_area+SUB +(1|Bloque), data = datos_hp)
mod_iwue_Parea_we= lmer(`iWUE (μmol/mol)`~ P_area+SUB +(1|Bloque), data = datos_Weinmania)

imod_iwue_Parea_pt = lmer(`iWUE (μmol/mol)`~ P_area*SUB +(1|Bloque), data = datos_Pouteria)
imod_iwue_Parea_cr= lmer(`iWUE (μmol/mol)`~ P_area*SUB +(1|Bloque), data = datos_Clarisia)
imod_iwue_Parea_al= lmer(`iWUE (μmol/mol)`~ P_area*SUB +(1|Bloque), data = datos_al)
imod_iwue_Parea_my= lmer(`iWUE (μmol/mol)`~ P_area*SUB +(1|Bloque), data = datos_myrcia)
imod_iwue_Parea_hp= lmer(`iWUE (μmol/mol)`~ P_area*SUB +(1|Bloque), data = datos_hp)
imod_iwue_Parea_we= lmer(`iWUE (μmol/mol)`~ P_area*SUB +(1|Bloque), data = datos_Weinmania)


summary(mod_iwue_Parea_pt)
summary(mod_iwue_Parea_cr)
summary(mod_iwue_Parea_al)
summary(mod_iwue_Parea_my)
summary(mod_iwue_Parea_hp)
summary(mod_iwue_Parea_we)
summary(imod_iwue_Parea_pt)
summary(imod_iwue_Parea_cr)
summary(imod_iwue_Parea_al)
summary(imod_iwue_Parea_my)
summary(imod_iwue_Parea_hp)
summary(imod_iwue_Parea_we)

#mod1 <- lmer(`iWUE (μmol/mol)` ~ SUB + (1|Bloque), data = datos_Clarisia)
#mod2 <- lmer(`iWUE (μmol/mol)` ~ Narea + SUB + (1|Bloque), data = datos_Clarisia)

#anova(mod1, mod2)
```
# Efectos graficos:
Se tendria que poner la significancia manualmente.





```{r}
#plot_model(mod_Nmass_al,vline.color = "red",show.values = TRUE, value.offset = .2)


#library(sjPlot)
#library(broom.mixed)
#library(dplyr)
#library(ggplot2)

# extraer p-values
#coefs <- broom.mixed::tidy(mod_Nmass_al) %>%
#  filter(effect == "fixed")

# vector de colores
#cols <- ifelse(coefs$p.value < 0.05, "red", "black")

# plot
#p <- plot_model(
#  mod_Nmass_al,
 # vline.color = "grey40",
 # show.values = TRUE,
 # value.offset = .2
#)

# cambiar colores

p 
```


```{r DHARMA diagnostics}
# Run and plot
#for (nm in names(models)) {
#  cat("\n", nm, "\n")
##  res <- simulateResiduals(models[[nm]], n = 1000)
#  plot(res, main = nm)
#}

#testUniformity(res)
#testDispersion(res)
#testOutliers(res)

#pdf("DHARMa_diagnostics_species_dummies.pdf", width = 9, height = 7)

#for (nm in names(models)) {
 # res <- simulateResiduals(models[[nm]], n = 1000)
#  plot(res, main = nm)
#}

#dev.off()

```








