#names sistematized
named13C_cellulose = "δ13C (‰ v.s.V-PDB)"
named13C_bulk = "bulk_δ13C (‰ v.s.V-PDB)"
name18O = "δ18O in ‰ vs DeltaSMOW"
named15N = "δ15N (‰ v.s.AIR)"
nameC_bulk ="[C_b]"
nameC_cellulose = "[C]"
thick = "thickness (mm)"
mthough = "mean though"
though = "force to punch (kN/m)"
LA = "Leaf area (cm²)"
SLA = "Specific leaf area (g/cm²)"
ratioCN = "C:N"
leaf_water = "leaf water content"
dry_matter = "dry mater content (mg/g)"
leaf_dry = "Leaf dry weight (g)"
leaf_fresh = "Leaf fresh weight (g)"